- name: Building iptables config file
  assemble: 
    src: /etc/sysconfig/iptables.d/ 
    dest: /etc/sysconfig/iptables
  register: iptables_service_policy
  when: manage_iptables

- name: Reloading custom iptables rule[s] if changed now
  service: 
    name: iptables 
    state: restarted
  when: iptables_service_policy is changed
  notify: restart_iptables

